#!/usr/bin/env bash

shopt -s globstar
release_dir=$1
ldd $release_dir/**/*/*.exe|grep -iv system32|grep -vi windows|grep -v :$  | cut -f2 -d\> | cut -f1 -d\( | tr '\\' '\/' |while read a; do ! [ -e "$release_dir/bin/`basename $a`" ] && cp -pv "$a" $release_dir/bin/; done
ldd $release_dir/**/*/*.dll|grep -iv system32|grep -vi windows|grep -v :$  | cut -f2 -d\> | cut -f1 -d\( | tr '\\' '\/' |while read a; do ! [ -e "$release_dir/bin/`basename $a`" ] && cp -pv "$a" $release_dir/bin/; done
exit 0