name: Build pages
on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-git
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-brotli
            mingw-w64-ucrt-x86_64-qt6
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-clang-libs
            mingw-w64-ucrt-x86_64-clang-tools-extra
            mingw-w64-ucrt-x86_64-llvm
            mingw-w64-ucrt-x86_64-llvm-libs

      - name: Build CodeBrowser
        run: |
          git clone https://github.com/hly1204/codebrowser.git
          cmake -B build-codebrowser -D CMAKE_BUILD_TYPE=Release -S codebrowser
          cmake --build build-codebrowser
          cmake --install build-codebrowser --strip --prefix=${MSYSTEM_PREFIX}

      - name: Generate docs
        id: build
        run: |
          cmake -B cmake-build-release \
                -D CMAKE_BUILD_TYPE=Release \
                -D CMAKE_WIN32_EXECUTABLE=ON \
                -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
                -D CMAKE_CXX_FLAGS_RELEASE="-DNDEBUG -O2 -march=nocona -msahf -mtune=generic -fcf-protection=full -fstack-protector-strong -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions" \
                -S .
          cmake --build cmake-build-release
          codebrowser_generator -p bilibilicardbrowser:`cygpath -m ${PWD}` \
                                -b `cygpath -m ${PWD}`/cmake-build-release -a \
                                -o html/code
          codebrowser_indexgenerator -o html/code
          cp -r ${MSYSTEM_PREFIX}/share/woboq/data html

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
